### ISSUE TITLE
C7S10 - Editting color schemes of some elements

### ISSUE THREAD

**Issue by TarekElsherif** [Sabrout/Kenllen#104]
All elements of the website should fit the general color scheme of the whole website.
Elements include:
- Font color
- Text fields
- Titles
- Cards
- Backgrounds

**Comment by TarekElsherif** [comment]
WonderPeople, review please!
@mohamedahmed3ali Code Review
@omarwaleed UML Review
@Sabrout Scenario Review
@abdelrahmanhamed Documentation Review

**Comment by omarwaleed** [comment]
everything looks good

**Comment by TarekElsherif** [comment]
@omarwaleed Please do Documentation review too for timing purposes

**Comment by Sabrout** [comment]
good :+1:
