### ISSUE TITLE
C6S06 As a user, i should be able to view the received message and reply to it

### ISSUE THREAD

**Issue by omarwaleed** [Sabrout/Kenllen#106]
When i view my inbox, strictly the inbox, if i press on the message body i am redirected to a page where the message body is viewed and there is a play to write my reply

Success Scenario:
Press on mail/inbox button, press on the body of any message, i am redirected to the reply page, the message is marked as read,  and if i write a message and send it it is sent to the recipient

Fail Scenarios:
if the i leave the body empty, nothing is sent

**Comment by omarwaleed** [comment]
@Sabrout documentation review
@TarekElsherif code review
@OmarElTayeb UML review
@mohamedahmed3ali scenario review

**Comment by TarekElsherif** [comment]
@omarwaleed Code reviewed. I commented few things to fix. Fix'em and you're good to go.

**Comment by Sabrout** [comment]
Documentation in the code is descriptive and useful .. Good Job :+1:

**Comment by mohamedahmed3ali** [comment]
Done reviewing the scenario, it worked properly, good job

**Comment by OmarElTayeb** [comment]
(Y)
