### ISSUE TITLE
AddImagesToItems

### ISSUE THREAD

**Issue by Zayko2010** [Sabrout/Kenllen#23]
Each item should have one or more images of the art itself:
- Create migration to create table of images for the items.
- Associate many images to one item.
- include add image field in create item view.
- view the first item image in the "item index" view, and "item show" view.

**Comment by Zayko2010** [comment]
@OmarElTayeb review my code
@OmarElTayeb review my code style
@OmarElTayeb review documentation

**Comment by OmarElTayeb** [comment]
@Zayko2010 you miss commentary, and the tests.

**Comment by Zayko2010** [comment]
@OmarElTayeb The comments are in progress, and the tests are done manually until I finish the documentation.
