### ISSUE TITLE
SignUpUsingFb

### ISSUE THREAD

**Issue by OmarElTayeb** [Sabrout/Kenllen#25]
A User can sign up by clicking on Facebook button which is present in sign in window.

**Comment by OmarElTayeb** [comment]
@Zayko2010 please review my code

**Comment by OmarElTayeb** [comment]
@Zayko2010 please review my documentation

**Comment by OmarElTayeb** [comment]
@Zayko2010 please review my scenairo

**Comment by Zayko2010** [comment]
@OmarElTayeb Work on your missing comments, and try to solve the error occurring when saving the user data in the database, which you showed in the bug label.
