### ISSUE TITLE
shoppingCart

### ISSUE THREAD

**Issue by abdoofathy95** [Sabrout/Kenllen#26]
- There is a cart button that redirects the user to his cart page
- There are two kinds of a cart (temporary cart and normal cart)
- temporary cart will be stored in session
- whether the user is a guest or not , user can add to his cart items , remove items
- in the cart page there are info about the added items (name , price , total price , quantity , item description , quantity in stock)
- there is a clear button to clear the whole cart
- there is a remove button to remove an item from the cart
- user can pick a quantity of his order by typing in a text field and updating his order
- user can continue shopping by clicking a continue button to be redirected to home page
- a checkout button to redirect to checkout page (if signed in else ask to sign-in or sign-up)

**Comment by TarekElsherif** [comment]
Just make the issue name CamelCase.

**Comment by abdoofathy95** [comment]
Done

**Comment by abdoofathy95** [comment]
@mohamedahmed3ali    Review the CodeStyle
@mohamedahmed3ali  Review The Code Documentation
@mohamedahmed3ali  Review Tests&Scenarios

**Comment by mohamedahmed3ali** [comment]
done testing. found no problems concerning code style or documentation or in tests.
