### ISSUE TITLE
ShopSessionControl

### ISSUE THREAD

**Issue by TarekElsherif** [Sabrout/Kenllen#29]
- A user can not create a shop unless he is logged in.
- A user edits, deletes, or add items to his own shops only.
- A user can edit or delete items only of his own shop.

**Comment by TarekElsherif** [comment]
@abdoofathy95 please review my code. @abdelrahmanhamed please review my documentation.

**Comment by abdoofathy95** [comment]
@TarekElsherif  
CodeReviewed:
item_controller indentation problem line:25-31 , line:48-55
shops_controller indentation problem line 11-13 missing a space ,line 77 missing space (indentation problem) , line 82:87 indentation problem , line 81-93 (indentation problem) 
shops_view_index.html.erb line 9-21 indentation problem (div indentation problem)
shops_view_show line 16-43 indentation problem , line 59-60 , line 63-64 indentation problem

Please Fix ASAP

**Comment by abdelrahmanhamed** [comment]
Documentation Review:
at item_controller there is no documentation on method delete and method destroy 
at shops_controller there is no documentatioa on methods show and new 
at index.html all good
at show.html all good 

over all good but try to comment ASAP
