### ISSUE TITLE
MustLogInBeforeBuying

### ISSUE THREAD

**Issue by abdelrahmanhamed** [Sabrout/Kenllen#31]
when a guest wants to buy any item he/she must log in to their account by a small form within the same page (popup form) . In case of not having an account he/she must sign up  by re directing him/her to the sign up page

**Comment by abdelrahmanhamed** [comment]
@abdoofathy95 plz review my code -- @TarekElsherif  plz review my scenario -- @TarekElsherif plz review my documntaion

**Comment by abdoofathy95** [comment]
@abdelrahmanhamed Code Reviewed (ALL GOOD)

**Comment by abdoofathy95** [comment]
@abdelrahmanhamed  CODE REVIEWED ( ALL GOOD)

**Comment by TarekElsherif** [comment]
app/views/carts/temporary_cart.html.erb => Line 62 irrelevant comment
Other than that, all good.
