### ISSUE TITLE
ShopLayout

### ISSUE THREAD

**Issue by mohamedahmed3ali** [Sabrout/Kenllen#34]
1.Changed the layout of the shop page to be more user friendly.

**Comment by mohamedahmed3ali** [comment]
@abdelrahmanhamed test my code

**Comment by mohamedahmed3ali** [comment]
@abdelrahmanhamed test my codeStyle 
@abdelrahmanhamed test my code review 
@abdelrahmanhamed review tests and scenario

**Comment by mohamedahmed3ali** [comment]
@abdelrahmanhamed test my codeStyle 
@abdelrahmanhamed test my code documentation
@abdelrahmanhamed review tests and scenario

**Comment by abdelrahmanhamed** [comment]
at show.html you need more documentation for the code it is all good but try to follow the code conventions more plz  for the scenario it is satisfying 

at show.scss for the documentation it is good for the code too and the scenario also good
