### ISSUE TITLE
HomePageView

### ISSUE THREAD

**Issue by abdelrahmanhamed** [Sabrout/Kenllen#35]
in this issue the view of the home page should at least contain the image slider and the items existed in the shops and if the user loged in he should see his/her porfile picture

**Comment by abdelrahmanhamed** [comment]
@mohamedahmed3ali plz review my code -- @TarekElsherif plz review my documntaion --  @TarekElsherif  plz review my scenario

**Comment by mohamedahmed3ali** [comment]
Review done, No problem concerning code style.

**Comment by TarekElsherif** [comment]
Checked documentation. It's okay.
