### ISSUE TITLE
FinilizedItemView

### ISSUE THREAD

**Issue by OmarElTayeb** [Sabrout/Kenllen#36]
in this issue the view of the Item page and Item in shop page should be finished

**Comment by OmarElTayeb** [comment]
@Zayko2010 please review my code style
@Zayko2010  please review my code documentation
@Zayko2010  please review my Scenario

**Comment by Zayko2010** [comment]
@OmarElTayeb you're missing some comments, which makes the code a little ambiguous, otherwise great work.
