### ISSUE TITLE
C6S01 Fixing messaging between Users

### ISSUE THREAD

**Issue by omarwaleed** [Sabrout/Kenllen#58]
This issue simply is a fix of the damage done by mailboxer gem which later changed to acts-as-messageable because simply the second one works and the first one doesn't.
The views are maintained but the controllers have been changed and compacted from "conversation_controller" and "messages_controller" to only the second one which saves alot of time and reduces the amount of complication in the code

Success scenarios:
1) a user is logged in presses on the mail button on top of the page, he is redirected to his inbox
2) a user composes a message and writes a correct recipient, the message is sent to the recipient's mailbox

Fail scenarios:
1) a user is not logged in presses on the mail button on top of the page, he is redirected to the sign in page, after signing in or signing up, he is redirected to his inbox
2) a user composes a message to a recipient that doesnt exist, the message is not sent and the page is re-rendered

**Comment by omarwaleed** [comment]
@Sabrout please review the scenarios of my work
@Zayko2010  please review my code and documentation

**Comment by Sabrout** [comment]
Please put the story ID on the issue name and put the success and failure scenarios. and Tag a 3rd person as @Zayko2010 has 2 reviews to do

**Comment by omarwaleed** [comment]
@abdelrahmanhamed please review my documentation

**Comment by omarwaleed** [comment]
@OmarElTayeb review my UML

**Comment by OmarElTayeb** [comment]
UML incomplete you should say what happen when user write a massage and click on sent massage and it can be more clearly you can make 4 big lines 1-User 2-View 3-Controller 4-models and there is a pointer from every one to place which it go

**Comment by Sabrout** [comment]
Composing Message works great and all .. but I can't delete any message and can't view sent message. so as a result I can't check my Trash

**Comment by omarwaleed** [comment]
@Sabrout  this is left for the next issue and not included in fix
@OmarElTayeb please recheck again the file has been changed as u asked

**Comment by Sabrout** [comment]
**If other reviews are good .. create a pull request to merge with master**

**Comment by abdelrahmanhamed** [comment]
good documentation but needs more explanation

**Comment by OmarElTayeb** [comment]
Nice work but if you want you can add the name of issue top-left the picture

**Comment by Sabrout** [comment]
BTW .. you should type the issue number every time you commit to link the code with the issue. a Note for coming issues

**Comment by Zayko2010** [comment]
@omarwaleed the code conventions are fine, only the "messages_controller.rb", has too many empty lines, and unused def's. If they won't be used, consider removing them. :)

**Comment by omarwaleed** [comment]
@Zayko2010  most of these defs are left for the next issue and will be used dont worry :D

**Comment by Zayko2010** [comment]
Ok, then code review is finished. :+1:
