### ISSUE TITLE
C7S05 -- As user i can send and recieve messages on good view 

### ISSUE THREAD

**Issue by abdelrahmanhamed** [Sabrout/Kenllen#62]
Success : the user should now be able to write the mail in good view 
Failure : none

in this issue the view of the mailing system should be more friendly than the old one

**Comment by abdelrahmanhamed** [comment]
@Sabrout senario review me please , @omarwaleed please review my code , @Zayko2010 please review my documentation

**Comment by omarwaleed** [comment]
code been reviewed and everything looks good

**Comment by Sabrout** [comment]
Scenarios are good. they don't clash with the previous interface of this story.
Note: Colors schemes and decorations are not final yet

**Comment by Zayko2010** [comment]
@abdelrahmanhamed ,The file "inbox.html.erb" needs more comments to make it clear, other than that the documentation is good.

**Comment by abdelrahmanhamed** [comment]
please @Zayko2010  change the labels

**Comment by Sabrout** [comment]
please rename the issue name to the format w agreed upon

**Comment by abdelrahmanhamed** [comment]
Done
