### ISSUE TITLE
C7S01 - Layout Improvements

### ISSUE THREAD

**Issue by Sabrout** [Sabrout/Kenllen#65]
**Success Scenario**
Navigation bar leads to Cart, Shop, Sign in, Sign out, Search and Mailbox.

**Fail Scenario**
Shop, Mailbox and Cart will be useless without Signing Up to be a user.

**Reviewers**
@mohamedahmed3ali  for Documentation Review
@abdelrahmanhamed   Scenario Review
@Zayko2010  Code Review

**Comment by abdelrahmanhamed** [comment]
done no problems were found

**Comment by abdoofathy95** [comment]
@Sabrout NOT ALLOWED TO DO A DOCUMENTATION REVIEW (DATABASE MASTER).

**Comment by Sabrout** [comment]
@abdoofathy95 sorry I'll assign someone else .. no need to shout in caps, you know :expressionless:

**Comment by mohamedahmed3ali** [comment]
Done reviewing Documentation .

**Comment by Zayko2010** [comment]
Code reviewed, all good

**Comment by abdelrahmanhamed** [comment]
done
