### ISSUE TITLE
C1S06 - I Can Search For Shops Or Items By name

### ISSUE THREAD

**Issue by TarekElsherif** [Sabrout/Kenllen#66]
- Users and Guests can search for Shops and Items by typing a string in the search text field and clicking the search button.
- The search should be protected from injection queries.
- Success Scenarios: 
  1) User/Guest enters a string in the search text field and clicks the search button
- Fail Scenarios:
  1) User/Guest enters an invalid string.
  2) User/Guest leaves the search field empty

**Comment by TarekElsherif** [comment]
Guys, review my work please
@mohamedahmed3ali Scenario Review
@Sabrout Code Review
@abdelrahmanhamed Documentation Review
@omarwaleed UML Review

**Comment by mohamedahmed3ali** [comment]
I tested the scenario, and it is working properly.

**Comment by Sabrout** [comment]
I've gone through all you code .. I commented on some unaligned lines and an empty one.
Fix them and you are good to go :rocket:

**Comment by TarekElsherif** [comment]
@Sabrout I'm done, check them and change the label

**Comment by Sabrout** [comment]
Hahahahahaha ... sorry but I couldn't resist commenting on these annoying little things :stuck_out_tongue_winking_eye:

**Comment by abdelrahmanhamed** [comment]
documentation reviewed good job

**Comment by omarwaleed** [comment]
UML verified... everything is good
