### ISSUE TITLE
C2S11 - User's Profile

### ISSUE THREAD

**Issue by mohamedahmed3ali** [Sabrout/Kenllen#68]
User/Guest can see his shops and the shops that he followed.

Success Scenarios: 
1) User/Guest clicks on profile button then sees his shops and followed shops. 

Fail Scenarios:
1) User/Guest didn't signup so won't be able to see profile button.

**Comment by mohamedahmed3ali** [comment]
@Sabrout please review my code documentation
@Zayko2010  please review my code 
@TarekElsherif   please review my scenario
@TarekElsherif   please review my UML

**Comment by Sabrout** [comment]
I've commented on **application.css** as there was a long comment was added there for no reason. Aside from that all you code is documented and ready to go. Good Job :blush: :thumbsup:

**Comment by Sabrout** [comment]
Please rename the issue to the format we agreed upon .. with the story ID
and please assign someone else to review your UMLs because I already reviewed your code documentation

**Comment by mohamedahmed3ali** [comment]
@Sabrout Please change the label of the documentation since you finished reviewing.

**Comment by TarekElsherif** [comment]
Scenario reviewed.

**Comment by Zayko2010** [comment]
Code Reviewed.
