### ISSUE TITLE
C7S04 - Finalized Item View

### ISSUE THREAD

**Issue by OmarElTayeb** [Sabrout/Kenllen#69]
Success scenarios:
Any guest can view items of shops which people put on web

Reviewers
@Sabrout  for Documentation Review
@Zayko2010  Scenario Review
@abdelrahmanhamed Code Review

**Comment by abdelrahmanhamed** [comment]
code reviewed good job

**Comment by abdoofathy95** [comment]
@OmarElTayeb  I can't Do a Documentation Review !!!!, I can Only Manage the Database .

**Comment by OmarElTayeb** [comment]
@Sabrout please review my Scenario Review 
@Zayko2010 please review my Code Review
@abdelrahmanhamed please review my Documentation

**Comment by abdelrahmanhamed** [comment]
done no problems were found

**Comment by Zayko2010** [comment]
The code indentation isn't correct. if conditions and div's should be reorganized.

**Comment by OmarElTayeb** [comment]
@Zayko2010 Done please reviewe again

**Comment by Zayko2010** [comment]
your code is ok
