### ISSUE TITLE
C2S09- ShopLayout

### ISSUE THREAD

**Issue by mohamedahmed3ali** [Sabrout/Kenllen#72]
success scenario: 
finalized design for shops.

**Comment by mohamedahmed3ali** [comment]
@abdelrahmanhamed  please review my scenario
@Sabrout  please review my code documentation
@TarekElsherif  please review my code

**Comment by abdelrahmanhamed** [comment]
scenario reviewed all good no problems

**Comment by TarekElsherif** [comment]
@mohamedahmed3ali Code reviewed. Check my comments in your code, fix them, and you're good to go.

**Comment by mohamedahmed3ali** [comment]
@TarekElsherif Done fixing what you commented on.
