### ISSUE TITLE
C7S09 - Forms styling for Shops and Items handling

### ISSUE THREAD

**Issue by TarekElsherif** [Sabrout/Kenllen#75]
CSS styling for forms of Shops and Items handling, which includes:
- shops/new
- shops/edit
- shops/delete
- items/new
- items/edit
- items/delete

No scenarios for this issue.

**Comment by TarekElsherif** [comment]
WonderPeople, please review!
@mohamedahmed3ali Scenario Review
@Zayko2010 Documentation Review
@OmarElTayeb Code Review

**Comment by OmarElTayeb** [comment]
you code review is good

**Comment by TarekElsherif** [comment]
@Sabrout Please review the scenarios.

**Comment by Sabrout** [comment]
Good to Go :+1:
