### ISSUE TITLE
C1S13 - User Can Report An Item

### ISSUE THREAD

**Issue by abdoofathy95** [Sabrout/Kenllen#77]
- Users Can Report Items That They See Not Fit
- A User Can Only Report An Item Once 
- Success Scenarios : 
  1) User Reports An Item and gets a success message.
- Fail Scenarios :
  1) User Can't Find a Button To report the item Since he/she already reported it.
  2) Guest Can't Find a Button To report the item Since he/she isn't Logged In.

**Comment by abdoofathy95** [comment]
@TarekElsherif  review the code
@mohamedahmed3ali review the scenarios
@omarwaleed  review the documentation

**Comment by TarekElsherif** [comment]
@abdoofathy95 Code review, I commented in your code one little thing to fix and you're good to go.

**Comment by abdoofathy95** [comment]
@TarekElsherif  fixed , check now

**Comment by mohamedahmed3ali** [comment]
@abdoofathy95 scenario reviewed, good job.

**Comment by omarwaleed** [comment]
documentation all good
