### ISSUE TITLE
C7S02 - Homepage Styling and Designing

### ISSUE THREAD

**Issue by Sabrout** [Sabrout/Kenllen#90]
**Success Scenario**
Homepage shows a slider of some artistic wallpapers and random/best items for guest and my items if signed in.
**Fail Scenario**
None

**Comment by Sabrout** [comment]
@OmarElTayeb Scenario Review
@TarekElsherif  Code Review
@mohamedahmed3ali  Documentation Review

**Comment by OmarElTayeb** [comment]
well done good job

**Comment by TarekElsherif** [comment]
@Sabrout Code Reviewed. Good thing you have OCD.

**Comment by mohamedahmed3ali** [comment]
done reviewing your code documentation.
