### ISSUE TITLE
C2S12-ProfileLayout

### ISSUE THREAD

**Issue by mohamedahmed3ali** [Sabrout/Kenllen#92]
success Scenario: 
the user will see his shops then his followed shops along with his personal information.

Fail scenario:
the user is not logged in, so the profile link will not be accessible.

**Comment by mohamedahmed3ali** [comment]
@OmarElTayeb please review my documentation
@TarekElsherif please review my code 
@abdelrahmanhamed  please review my Scenario

**Comment by TarekElsherif** [comment]
@mohamedahmed3ali Code reviewed. Minor issues to fix, and you're good to go.

**Comment by abdelrahmanhamed** [comment]
scenario reviewed  good job

**Comment by OmarElTayeb** [comment]
add a description for every main div

**Comment by OmarElTayeb** [comment]
Nice work you can merge now

**Comment by mohamedahmed3ali** [comment]
@OmarElTayeb change the label please
