### ISSUE TITLE
C3S04 - As a user I can rate Items.

### ISSUE THREAD

**Issue by OmarElTayeb** [Sabrout/Kenllen#93]
As User/Guest I can rate to any item .

Success Scenarios:

Add a rating to an item, which affects its overall rating.

**Comment by OmarElTayeb** [comment]
@Zayko2010 please code review 
@TarekElsherif  please scenario review 
@omarwaleed UML review
@mohamedahmed3ali  Documentation Review

**Comment by mohamedahmed3ali** [comment]
done reviewing code Documentation

**Comment by Zayko2010** [comment]
@OmarElTayeb the file Item/show.html.erb, conventions are wrong. 
Fix it and you're done.

**Comment by OmarElTayeb** [comment]
done review again

**Comment by omarwaleed** [comment]
done everything is good

**Comment by Zayko2010** [comment]
Code reviewed again, all good.

**Comment by TarekElsherif** [comment]
@OmarElTayeb Scenario Reviewed.
