### ISSUE TITLE
C6S05 As a user i should be able to check my trashbox

### ISSUE THREAD

**Issue by omarwaleed** [Sabrout/Kenllen#95]
When a user logs in, he can delete his inbox messages and can check these messages from his trash

Success scenarios:
1) Log in, press on mail button, press on delete for any message to send it and then redirected to trash
2) Log in, press on mail button, press on  trashbox button to go to the trash

Fail Scenarios:
None

**Comment by omarwaleed** [comment]
@Sabrout scenario view
@OmarElTayeb UML review
@mohamedahmed3ali documentation review
@Zayko2010 code review plz

**Comment by Sabrout** [comment]
Scenarios are OK .. it's Scenario review not "view" btw :stuck_out_tongue:

**Comment by OmarElTayeb** [comment]
you should spilt view in UML to all views you used

**Comment by omarwaleed** [comment]
@OmarElTayeb done... rereview plz

**Comment by OmarElTayeb** [comment]
Done great work

**Comment by Zayko2010** [comment]
Code Reviewed.

**Comment by omarwaleed** [comment]
@abdelrahmanhamed documentation review for timing purposes

**Comment by abdelrahmanhamed** [comment]
there are no single commit to this issue that i can track ur work with but tell me which branch so i can check there

**Comment by omarwaleed** [comment]
@abdelrahmanhamed i referenced the branch top of this page

**Comment by abdelrahmanhamed** [comment]
ok done the documentation is good
